# Generated by Django 4.0.4 on 2022-04-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footprints',
            fields=[
                ('FootprintId', models.AutoField(primary_key=True, serialize=False)),
                ('FootrpintValue', models.DecimalField(decimal_places=2, max_digits=4)),
                ('FootprintGender', models.CharField(max_length=100)),
                ('FootprintCountry', models.CharField(max_length=200)),
                ('FootprintAge', models.IntegerField()),
            ],
        ),
    ]
