# Generated by Django 4.0.4 on 2022-04-22 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footprints',
            old_name='FootrpintValue',
            new_name='FootprintValue',
        ),
    ]
